### PR TITLE
Add emoji support

### PR DESCRIPTION
**Pull request by mkautzmann**
As discussed in #499, it would be cool to support emoji.

## Implementation

The idea is to replace any text [emoji references](http://www.emoji-cheat-sheet.com/) with `img` tags loading the respective icon. That is accomplished using a custom `handlebars` helper that I'm calling `render_emoji` with the help of [emojify.js](http://hassankhan.me/emojify.js/). It will not get in the way of unicode emoji as it should be rendered by the user's system.

This proposal is the simplest one I could come up with. It kinda mimics the way GitHub displays emojis so it should work well in all repos.

Rendering on the server is important here so it only loads the symbols used in the current page and not the whole emoji set. The impact on page load performance is low and depends on the amount of emoji being displayed.

In fact, we are using GitHub's emoji repository via their own CDN so we don't have to host the images and, as bonus, we stay in sync with GitHub.

Supporting new emojis in the future should be as easy as updating `emojify.js`.

## Tests

Emojis should be rendering in the following views:

- Index
- Search
- Repo
- Owner

Since there's no automated test mechanism in place I've performed several manual/visual tests on the following browsers with success:

- IE11
- MS Edge
- Chrome
- Firefox
- Safari
- Opera

### Viewing on card
card_view

### Viewing on repo description
repo_view

### Viewing on repo README
readme_view

### CODE REVIEW

**Comment by zenorocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
It works perfectly! Thanks a lot @mkautzmann, you rock! :fire:

**Comment by mkautzmann** [comment]
:+1:  Cool! Looking forward to submit some custom elements I'm working on to the website too.

**Comment by zenorocha** [comment]
Yay!!

**Pull request merged**
